application: yourpixx
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /
  static_files: index.html
  upload: index.html
  
- url: /(.+)
  static_files: \1
  upload: (.+)
 
  
  